(() => {
  const state={events:[],lang:"de",todayExpanded:false,weekendExpanded:false,shortExpanded:false,longExpanded:false,newExpanded:false};
  const $=s=>document.querySelector(s);
  const txt={
    de:{today:"Heute",weekend:"Dieses Wochenende",todayIntro:"Was heute konkret stattfindet",weekendIntro:"Kurzveranstaltungen am kommenden Wochenende",regions:"Nach Region entdecken",where:"Wohin möchtest du?",find:"Finde dein Event",browse:"Alle Events durchsuchen",from:"Von",to:"Bis",area:"Region",category:"Kategorie",search:"Suche",reset:"Zurücksetzen",sort:"Sortierung",soonest:"Nächste zuerst",latest:"Späteste zuerst",place:"Nach Ort",todayBtn:"Heute",weekBtn:"Diese Woche",nextWeek:"Nächste Woche",weekendBtn:"Wochenende",month:"Dieser Monat",all12:"Nächste 12 Monate",shortTitle:"Termine & Kurzveranstaltungen",longTitle:"Langzeit & Dauerausstellungen",longIntro:"Ausstellungen, Saisonprogramme und wiederkehrende Angebote, die über mehrere Wochen laufen.",details:"Details",official:"Offizielle Eventseite",date:"Datum",time:"Uhrzeit",location:"Ort",venue:"Veranstaltungsort",organizer:"Veranstalter",admission:"Eintritt",source:"Quelle",verified:"Geprüft",allAreas:"Alle Regionen",allCats:"Alle Kategorien",all:"Alle",lastVerified:"letzte Datenprüfung",newAdded:"neu hinzugefügt",newTitle:"Neu seit der letzten Aktualisierung",more:"weitere",less:"weniger",noToday:"Heute sind keine kurzen Einzeltermine eingetragen.",noWeekend:"Für dieses Wochenende sind keine kurzen Einzeltermine eingetragen.",noShort:"Keine Kurzveranstaltungen für diesen Zeitraum.",newNone:"Keine neu hinzugefügten Events.",footerTag:"Ein kuratierter Eventguide für das gesamte Trentino.",footerA:"Zeitraum:",footerB:"Daten und Programme können sich ändern. Maßgeblich ist die offizielle Veranstalterseite.",groups:{culture:"Kultur",family:"Kinder & Familien",markets:"Märkte",food:"Genuss & Tradition",sport:"Sport & Outdoor",festival:"Festivals & Feste",business:"Business & Messen",other:"Sonstiges"}},
    en:{today:"Today",weekend:"This weekend",todayIntro:"What is actually happening today",weekendIntro:"Short events this coming weekend",regions:"Explore by area",where:"Where do you want to go?",find:"Find your event",browse:"Browse all events",from:"From",to:"To",area:"Area",category:"Category",search:"Search",reset:"Reset",sort:"Sort",soonest:"Soonest first",latest:"Latest first",place:"By place",todayBtn:"Today",weekBtn:"This week",nextWeek:"Next week",weekendBtn:"Weekend",month:"This month",all12:"Next 12 months",shortTitle:"Dates & short events",longTitle:"Long-running events & exhibitions",longIntro:"Exhibitions, seasonal programmes and recurring activities that run for several weeks.",details:"Details",official:"Official event page",date:"Date",time:"Time",location:"Location",venue:"Venue",organizer:"Organizer",admission:"Admission",source:"Source",verified:"Verified",allAreas:"All areas",allCats:"All categories",all:"All",lastVerified:"last database check",newAdded:"newly added",newTitle:"New since the last update",more:"more",less:"less",noToday:"No short one-off events are listed for today.",noWeekend:"No short one-off events are listed for this weekend.",noShort:"No short events match this period.",newNone:"No newly added events.",footerTag:"A curated guide to what’s happening across Trentino.",footerA:"Rolling window:",footerB:"Dates and programmes can change. The official organizer page remains the source of truth.",groups:{culture:"Culture",family:"Kids & Family",markets:"Markets",food:"Food, Wine & Tradition",sport:"Sport & Outdoor",festival:"Festivals & Fairs",business:"Business & Trade",other:"Other"}},
    it:{today:"Oggi",weekend:"Questo weekend",todayIntro:"Cosa succede concretamente oggi",weekendIntro:"Eventi brevi del prossimo weekend",regions:"Esplora per zona",where:"Dove vuoi andare?",find:"Trova il tuo evento",browse:"Esplora tutti gli eventi",from:"Da",to:"A",area:"Zona",category:"Categoria",search:"Cerca",reset:"Azzera",sort:"Ordina",soonest:"Prima i più vicini",latest:"Prima i più lontani",place:"Per luogo",todayBtn:"Oggi",weekBtn:"Questa settimana",nextWeek:"Prossima settimana",weekendBtn:"Weekend",month:"Questo mese",all12:"Prossimi 12 mesi",shortTitle:"Appuntamenti ed eventi brevi",longTitle:"Eventi di lunga durata e mostre",longIntro:"Mostre, programmi stagionali e attività ricorrenti che durano diverse settimane.",details:"Dettagli",official:"Pagina ufficiale",date:"Data",time:"Ora",location:"Località",venue:"Luogo",organizer:"Organizzatore",admission:"Ingresso",source:"Fonte",verified:"Verificato",allAreas:"Tutte le zone",allCats:"Tutte le categorie",all:"Tutte",lastVerified:"ultimo controllo database",newAdded:"nuovi aggiunti",newTitle:"Nuovi dall’ultimo aggiornamento",more:"altri",less:"meno",noToday:"Oggi non risultano appuntamenti brevi.",noWeekend:"Per questo weekend non risultano appuntamenti brevi.",noShort:"Nessun evento breve per questo periodo.",newNone:"Nessun nuovo evento aggiunto.",footerTag:"Una guida curata agli eventi in tutto il Trentino.",footerA:"Finestra mobile:",footerB:"Date e programmi possono cambiare. Fa fede la pagina ufficiale dell’organizzatore.",groups:{culture:"Cultura",family:"Bambini & Famiglie",markets:"Mercati",food:"Gusto & Tradizione",sport:"Sport & Outdoor",festival:"Festival & Feste",business:"Business & Fiere",other:"Altro"}}
  };
  const locale=()=>state.lang==="de"?"de-DE":state.lang==="it"?"it-IT":"en-GB";
  const pools={default:["https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1000&q=80"],market:["https://images.unsplash.com/photo-1488459716781-31db52582fe9?auto=format&fit=crop&w=1000&q=80"],food:["https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?auto=format&fit=crop&w=1000&q=80"],culture:["https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&w=1000&q=80"],festival:["https://images.unsplash.com/photo-1506157786151-b8491531f063?auto=format&fit=crop&w=1000&q=80"],outdoor:["https://images.unsplash.com/photo-1461896836934-ffe607ba8211?auto=format&fit=crop&w=1000&q=80"],business:["https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1000&q=80"]};
  const areaImages={"Rovereto & Vallagarina":"https://images.unsplash.com/photo-1467269204594-9661b134dd2b?auto=format&fit=crop&w=800&q=78","Trento":"https://images.unsplash.com/photo-1529260830199-42c24126f198?auto=format&fit=crop&w=800&q=78","Alto Garda":"https://images.unsplash.com/photo-1530789253388-582c481c54b0?auto=format&fit=crop&w=800&q=78","Other Trentino":"https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=78"};
  function nowRome(){const p=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Rome",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date());const g=t=>p.find(x=>x.type===t)?.value;return `${g("year")}-${g("month")}-${g("day")}`}
  const TODAY=nowRome();
  function dateOnly(s){const [y,m,d]=String(s).split("-").map(Number);return new Date(Date.UTC(y,m-1,d))}
  function iso(d){return d.toISOString().slice(0,10)}
  function addDays(s,n){const d=dateOnly(s);d.setUTCDate(d.getUTCDate()+n);return iso(d)}
  function plusYear(s){const d=dateOnly(s);d.setUTCFullYear(d.getUTCFullYear()+1);return iso(d)}
  function fmt(s,o={day:"numeric",month:"short",year:"numeric"}){return new Intl.DateTimeFormat(locale(),{...o,timeZone:"UTC"}).format(dateOnly(s))}
  function range(a,b){return a===b?fmt(a):`${fmt(a)} – ${fmt(b)}`}
  function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
  function name(e){return e.name?.[state.lang]||e.name?.it||e.name?.en||""}
  function active(e){return !["REMOVED","CANCELLED"].includes(e.status)&&e.endDate>=TODAY}
  function overlaps(e,a,b){return e.endDate>=a&&e.startDate<=b}
  function duration(e){return Math.max(1,Math.round((dateOnly(e.endDate)-dateOnly(e.startDate))/86400000)+1)}
  function longTerm(e){return duration(e)>21||!!e.recurrence||Array.isArray(e.occurrences)}
  function groupKey(e){const c=(e.category||"").toLowerCase();if(c.includes("family")||c.includes("child"))return "family";if(c.includes("culture")||c.includes("film")||c.includes("concert")||c.includes("dance")||c.includes("exhibition")||c.includes("music"))return "culture";if(c.includes("market")||c.includes("shopping")||c.includes("christmas"))return "markets";if(c.includes("wine")||c.includes("gastronomy")||c.includes("food")||c.includes("agriculture")||c.includes("tradition"))return "food";if(c.includes("sport")||c.includes("outdoor"))return "sport";if(c.includes("festival")||c.includes("fair"))return "festival";if(c.includes("business")||c.includes("trade"))return "business";return "other"}
  function groupLabel(e){return txt[state.lang].groups[groupKey(e)]}
  function image(e){if(e.image)return e.image;return pools[groupKey(e)]?.[0]||pools.default[0]}
  function validDescription(e){const d=e.description?.[state.lang]||e.description?.en||e.description?.it||"";return d&&!/Aktuelle Details finden Sie|See the official event page|Consulta la pagina ufficiale/i.test(d)?d:""}
  function summary(e){const existing=validDescription(e);if(existing)return existing;const n=name(e),p=e.municipality||e.area||"Trentino",v=e.venue&&e.venue!==p?e.venue:"",r=range(e.startDate,e.endDate),g=groupKey(e);if(state.lang==="de"){const intro={culture:`„${n}“ ist ein Kulturtermin in ${p}.`,family:`„${n}“ ist ein Angebot für Kinder und Familien in ${p}.`,markets:`„${n}“ ist ein Markt- oder Einkaufstermin in ${p}.`,food:`„${n}“ steht für Genuss, regionale Tradition oder Kulinarik in ${p}.`,sport:`„${n}“ ist ein Sport- oder Outdoor-Termin in ${p}.`,festival:`„${n}“ ist ein Festival- oder Festtermin in ${p}.`,business:`„${n}“ ist ein Business- oder Messetermin in ${p}.`,other:`„${n}“ ist eine Veranstaltung in ${p}.`}[g];return `${intro} Der Termin läuft ${r}${v?` am Veranstaltungsort ${v}`:""}${e.startTime?` ab ${e.startTime} Uhr`:""}. So sind Zeitraum und Ort auf einen Blick klar, bevor du bei Bedarf das vollständige Programm öffnest.`}if(state.lang==="it"){const intro={culture:`“${n}” è un appuntamento culturale a ${p}.`,family:`“${n}” è un’attività per bambini e famiglie a ${p}.`,markets:`“${n}” è un appuntamento dedicato a mercati o shopping a ${p}.`,food:`“${n}” è legato a gusto, prodotti locali o tradizione a ${p}.`,sport:`“${n}” è un appuntamento sportivo o outdoor a ${p}.`,festival:`“${n}” è un festival o una festa a ${p}.`,business:`“${n}” è un appuntamento business o fieristico a ${p}.`,other:`“${n}” è un evento a ${p}.`}[g];return `${intro} Si svolge ${r}${v?` presso ${v}`:""}${e.startTime?` dalle ${e.startTime}`:""}. In questo modo data e luogo sono subito chiari prima di aprire il programma completo.`}const intro={culture:`“${n}” is a cultural event in ${p}.`,family:`“${n}” is an activity for children and families in ${p}.`,markets:`“${n}” is a market or shopping event in ${p}.`,food:`“${n}” focuses on food, local products or tradition in ${p}.`,sport:`“${n}” is a sport or outdoor event in ${p}.`,festival:`“${n}” is a festival or local celebration in ${p}.`,business:`“${n}” is a business or trade event in ${p}.`,other:`“${n}” is an event in ${p}.`}[g];return `${intro} It runs ${r}${v?` at ${v}`:""}${e.startTime?` from ${e.startTime}`:""}. This gives you the key timing and location before opening the full programme.`}
  function latestVerified(){return state.events.map(e=>e.verified).filter(Boolean).sort().at(-1)||TODAY}
  function newlyAdded(){const latest=latestVerified();return state.events.filter(active).filter(e=>(e.status==="NEW"&&(e.statusDate||e.verified)===latest)||(e.discoveredVia==="coverage_backfill"&&e.verified===latest))}
  function getWeekend(){const d=dateOnly(TODAY),dow=d.getUTCDay(),toSat=(6-dow+7)%7,sat=addDays(TODAY,toSat);return [sat,addDays(sat,1)]}
  function card(e){return `<article class="event-card"><div class="event-image-wrap"><img class="event-image" src="${esc(image(e))}" alt="${esc(name(e))}" loading="lazy"><div class="date-chip"><div class="day">${String(dateOnly(e.startDate).getUTCDate()).padStart(2,"0")}</div><div class="mon">${esc(new Intl.DateTimeFormat(locale(),{month:"short",timeZone:"UTC"}).format(dateOnly(e.startDate)))}</div></div></div><div class="card-body"><div class="category">${esc(groupLabel(e))}</div><h3>${esc(name(e))}</h3><p class="meta"><strong>${esc(e.municipality||"")}</strong>${e.venue&&e.venue!==e.municipality?` · ${esc(e.venue)}`:""}<br>${esc(range(e.startDate,e.endDate))}${e.startTime?` · ${esc(e.startTime)}`:""}</p><p class="desc">${esc(summary(e))}</p><div class="card-actions"><span class="source-mini">${esc(e.source||"")}</span><button type="button" class="details-btn" data-open="${esc(e.id)}">${esc(txt[state.lang].details)} →</button></div></div></article>`}
  function focusCard(e){return `<article class="focus-event"><div class="focus-event-image"><img src="${esc(image(e))}" alt="${esc(name(e))}" loading="lazy"></div><div class="focus-event-body"><div class="mini-category">${esc(groupLabel(e))}</div><h3>${esc(name(e))}</h3><p>${esc(e.municipality||"")} · ${esc(range(e.startDate,e.endDate))}</p><button type="button" data-open="${esc(e.id)}">${esc(txt[state.lang].details)} →</button></div></article>`}
  function compactLong(e){return `<article class="longterm-card"><img src="${esc(image(e))}" alt="${esc(name(e))}" loading="lazy"><div class="longterm-body"><div><span class="longterm-tag">${esc(groupLabel(e))}</span><h3>${esc(name(e))}</h3><p>${esc(e.municipality||"")} · ${esc(range(e.startDate,e.endDate))}</p></div><button type="button" data-open="${esc(e.id)}">${esc(txt[state.lang].details)} →</button></div></article>`}
  function bindOpen(root=document){root.querySelectorAll("[data-open]").forEach(b=>b.onclick=()=>openEvent(b.dataset.open));root.querySelectorAll("img").forEach(i=>i.onerror=()=>{i.src=pools.default[0]})}
  function openEvent(id){const e=state.events.find(x=>x.id===id);if(!e)return;const t=txt[state.lang];const item=(l,v)=>`<div class="detail-item"><span>${esc(l)}</span><strong>${esc(v||"—")}</strong></div>`;$("#dialogBody").innerHTML=`<div class="detail-hero"><img src="${esc(image(e))}" alt="${esc(name(e))}"></div><div class="detail-content"><div class="detail-kicker">${esc(groupLabel(e))} · ${esc(e.area||"")}</div><h2>${esc(name(e))}</h2><p>${esc(summary(e))}</p><div class="detail-grid">${item(t.date,range(e.startDate,e.endDate))}${item(t.time,e.startTime)}${item(t.location,e.municipality)}${item(t.venue,e.venue)}${item(t.organizer,e.organizer)}${item(t.admission,/See official page/i.test(e.price||"")?"—":e.price)}${item(t.source,e.source)}${item(t.verified,e.verified?fmt(e.verified):"—")}</div>${e.officialUrl?`<a class="official-link" href="${esc(e.officialUrl)}" target="_blank" rel="noopener noreferrer">${esc(t.official)} ↗</a>`:""}</div>`;bindOpen($("#dialogBody"));$("#eventDialog").showModal()}
  function filtered(){const from=$("#fromDate").value||TODAY,to=$("#toDate").value||plusYear(TODAY),area=$("#areaFilter").value,grp=$("#categoryFilter").value,q=$("#searchInput").value.trim().toLowerCase();let a=state.events.filter(active).filter(e=>overlaps(e,from,to)).filter(e=>!area||e.area===area).filter(e=>!grp||groupKey(e)===grp).filter(e=>!q||[name(e),e.municipality,e.area,e.venue,e.category,summary(e)].filter(Boolean).join(" ").toLowerCase().includes(q));const s=$("#sortSelect").value;a.sort((x,y)=>s==="latest"?y.startDate.localeCompare(x.startDate):s==="place"?String(x.municipality).localeCompare(String(y.municipality)):x.startDate.localeCompare(y.startDate));return a}
  function renderNew(){const list=newlyAdded(),b=$("#newEventsToggle");b.textContent=`+${list.length} ${txt[state.lang].newAdded}`;b.disabled=!list.length;$("#newEventsPanel").hidden=!state.newExpanded||!list.length;$("#newEventsPanelTitle").textContent=txt[state.lang].newTitle;$("#newEventList").innerHTML=list.map(e=>`<button class="new-event-item" data-open="${esc(e.id)}"><span><strong>${esc(name(e))}</strong><br>${esc(e.municipality||"")}</span><span>${esc(fmt(e.startDate,{day:"2-digit",month:"short"}))}</span></button>`).join("");bindOpen($("#newEventList"))}
  function renderFocus(){const short=state.events.filter(active).filter(e=>!longTerm(e)).sort((a,b)=>a.startDate.localeCompare(b.startDate));const today=short.filter(e=>overlaps(e,TODAY,TODAY));const [sat,sun]=getWeekend(),weekend=short.filter(e=>overlaps(e,sat,sun));renderFocusBlock("todayGrid","todayMore",today,state.todayExpanded,"todayExpanded",txt[state.lang].noToday);renderFocusBlock("weekendGrid","weekendMore",weekend,state.weekendExpanded,"weekendExpanded",txt[state.lang].noWeekend)}
  function renderFocusBlock(gridId,btnId,arr,expanded,key,empty){const grid=$("#"+gridId),btn=$("#"+btnId),visible=expanded?arr:arr.slice(0,2);grid.innerHTML=visible.length?visible.map(focusCard).join(""):`<p>${esc(empty)}</p>`;btn.hidden=arr.length<=2;btn.textContent=expanded?`− ${txt[state.lang].less}`:`+ ${arr.length-2} ${txt[state.lang].more}`;btn.onclick=()=>{state[key]=!state[key];renderFocus()};bindOpen(grid)}
  function renderArea(){const activeEvents=state.events.filter(active),areas=[...new Set(activeEvents.map(e=>e.area).filter(Boolean))];$("#areaCards").innerHTML=areas.map(a=>`<button type="button" class="area-card" data-area="${esc(a)}"><img src="${esc(areaImages[a]||areaImages["Other Trentino"])}" alt="" loading="lazy"><span class="area-card-content"><strong>${esc(a)}</strong><span>${activeEvents.filter(e=>e.area===a).length} Events</span></span></button>`).join("");document.querySelectorAll(".area-card").forEach(b=>b.onclick=()=>{$("#areaFilter").value=b.dataset.area;renderLists();$("#discover").scrollIntoView({behavior:"smooth"})})}
  function renderLists(){const all=filtered(),short=all.filter(e=>!longTerm(e)),long=all.filter(longTerm);renderLimited("eventsGrid","shortMore",short,state.shortExpanded,"shortExpanded",card,txt[state.lang].noShort);renderLimited("longTermGrid","longMore",long,state.longExpanded,"longExpanded",compactLong,"");$("#longTermSection").hidden=!long.length;$("#rangeLabel").textContent=`${range($("#fromDate").value,$("#toDate").value)} · ${short.length} ${txt[state.lang].shortTitle.toLowerCase()}`}
  function renderLimited(gridId,btnId,arr,expanded,key,renderer,empty){const grid=$("#"+gridId),btn=$("#"+btnId),visible=expanded?arr:arr.slice(0,5);grid.innerHTML=visible.length?visible.map(renderer).join(""):(empty?`<p>${esc(empty)}</p>`:"");btn.hidden=arr.length<=5;btn.textContent=expanded?`− ${txt[state.lang].less}`:`+ ${arr.length-5} ${txt[state.lang].more}`;btn.onclick=()=>{state[key]=!state[key];renderLists()};bindOpen(grid)}
  function setLanguage(){const t=txt[state.lang];document.documentElement.lang=state.lang;document.querySelectorAll("[data-i18n]").forEach(e=>{const k=e.dataset.i18n;if(t[k])e.textContent=t[k]});$("#searchInput").placeholder=state.lang==="de"?"Event, Ort, Veranstaltungsort…":state.lang==="it"?"Evento, località, luogo…":"Event, place, venue…";$("#rollingWindow").textContent=`${fmt(TODAY)} – ${fmt(plusYear(TODAY))}`;buildFilters();renderAll()}
  function buildFilters(){const t=txt[state.lang],areaVal=$("#areaFilter").value,catVal=$("#categoryFilter").value,areas=[...new Set(state.events.map(e=>e.area).filter(Boolean))].sort(),groups=["culture","family","markets","food","sport","festival","business","other"];$("#areaFilter").innerHTML=`<option value="">${t.allAreas}</option>`+areas.map(a=>`<option value="${esc(a)}">${esc(a)}</option>`).join("");$("#categoryFilter").innerHTML=`<option value="">${t.allCats}</option>`+groups.map(g=>`<option value="${g}">${esc(t.groups[g])}</option>`).join("");$("#areaFilter").value=areaVal;$("#categoryFilter").value=catVal;$("#categoryChips").innerHTML=`<button class="category-chip ${catVal?"":"active"}" data-group="">${t.all}</button>`+groups.map(g=>`<button class="category-chip ${catVal===g?"active":""}" data-group="${g}">${esc(t.groups[g])}</button>`).join("");document.querySelectorAll("[data-group]").forEach(b=>b.onclick=()=>{$("#categoryFilter").value=b.dataset.group;document.querySelectorAll("[data-group]").forEach(x=>x.classList.toggle("active",x===b));state.shortExpanded=state.longExpanded=false;renderLists()})}
  function quick(which){let from=TODAY,to=plusYear(TODAY),d=dateOnly(TODAY),dow=d.getUTCDay();if(which==="today")to=TODAY;if(which==="week")to=addDays(TODAY,6);if(which==="nextweek"){from=addDays(TODAY,7);to=addDays(from,6)}if(which==="weekend"){[from,to]=getWeekend()}if(which==="month")to=iso(new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+1,0)));$("#fromDate").value=from;$("#toDate").value=to;document.querySelectorAll("[data-quick]").forEach(b=>b.classList.toggle("active",b.dataset.quick===which));state.shortExpanded=state.longExpanded=false;renderLists()}
  function renderAll(){const latest=latestVerified();$("#lastVerified").textContent=fmt(latest,{day:"2-digit",month:"short",year:"numeric"});renderNew();renderFocus();renderArea();renderLists()}
  function bind(){document.querySelectorAll(".lang").forEach(b=>b.onclick=()=>{state.lang=b.dataset.lang;document.querySelectorAll(".lang").forEach(x=>x.classList.toggle("active",x===b));setLanguage()});["fromDate","toDate","areaFilter","categoryFilter","sortSelect"].forEach(id=>$("#"+id).onchange=()=>{state.shortExpanded=state.longExpanded=false;renderLists()});$("#searchInput").oninput=renderLists;document.querySelectorAll("[data-quick]").forEach(b=>b.onclick=()=>quick(b.dataset.quick));$("#resetFilters").onclick=()=>{$("#fromDate").value=TODAY;$("#toDate").value=plusYear(TODAY);$("#areaFilter").value="";$("#categoryFilter").value="";$("#searchInput").value="";$("#sortSelect").value="soonest";document.querySelectorAll("[data-quick]").forEach(b=>b.classList.toggle("active",b.dataset.quick==="all"));buildFilters();renderLists()};$("#newEventsToggle").onclick=()=>{state.newExpanded=!state.newExpanded;renderNew()};$("#closeDialog").onclick=()=>$("#eventDialog").close();$("#eventDialog").onclick=e=>{if(e.target===$("#eventDialog"))$("#eventDialog").close()}}
  async function load(){try{const r=await fetch("data/events.json",{cache:"no-store"});state.events=await r.json()}catch(e){$("#eventsGrid").innerHTML="<p>data/events.json could not be loaded.</p>";return}$("#fromDate").value=TODAY;$("#toDate").value=plusYear(TODAY);buildFilters();bind();setLanguage()}
  load();
})();